config/routes.rb
Greasyfork::Application.routes.draw do

	get 'sso', :to => 'home#sso'

	scope "(:locale)", locale: /ar|bg|cs|de|el|en|es|fi|fr|fr\-CA|id|it|ja|nb|nl|pl|pt\-BR|ru|tr|uk|vi|zh\-CN|zh\-TW/ do

		get '/users', :to => 'users#index', :as => 'users'
		get '/users/webhook-info', :to => 'users#webhook_info', :as => 'user_webhook_info'
		post 'users/webhook-info', :to => 'users#webhook_info'
		get '/users/edit_sign_in' => 'users#edit_sign_in', :as => 'user_edit_sign_in'
		delete '/users/identities' => 'users#delete_identity', :as => 'user_delete_identity'
		put '/users/identities' => 'users#update_identity', :as => 'user_update_identity'
		put '/users/remove_password' => 'users#remove_password', :as => 'user_remove_password'
		put '/users/update_password' => 'users#update_password', :as => 'user_update_password'

		get '/external_login', :as => 'external_login', to: 'home#external_login'

		devise_for :users, :skip => :registrations, :controllers => { :sessions => "sessions" }
		devise_scope :user do
			resource :registration,
			only: [:new, :create, :edit, :update],
			path: 'users',
			path_names: { new: 'sign_up' },
			controller: :registrations,
			as: :user_registration do
				get :cancel
			end
		end
		devise_scope :user do
			get '/users/sign_out' => 'sessions#destroy'
			get '/auth/:provider/callback', to: 'sessions#omniauth_callback', :as => 'omniauth_callback'
			post '/auth/:provider/callback', to: 'sessions#omniauth_callback'
			get '/auth/failure', to: 'sessions#omniauth_failure'
			get '/auth/failure2', to: 'sessions#omniauth_failure'
			post '/auth/name_conflict', to: 'sessions#name_conflict'
		end

		root :to => "home#index"

		get 'scripts/sync_additional_info_form', :to => 'scripts#sync_additional_info_form', :as => 'script_sync_additional_info_form'
		resources :scripts, :only => [:index, :show] do
			get 'code.meta.js', :to => 'scripts#meta_js', :locale => nil
			get 'code.user.js', :to => 'scripts#user_js', :locale => nil

			get 'code/:name.user.js', :to => 'scripts#user_js', :as =>  'user_js', :locale => nil
			get 'code/:name.js', :to => 'scripts#user_js', :as =>  'library_js', :locale => nil
			get 'code/:name.meta.js', :to => 'scripts#meta_js', :as =>  'meta_js', :locale => nil
			match 'code/:name.meta.js', :to => 'scripts#meta_js', :locale => nil, :via => :options
			get 'code(.:format)', :to => 'scripts#show_code', :as =>  'show_code', :constraints => {:format => /.*/}
			get 'feedback(.:format)', :to => 'scripts#feedback', :as =>  'feedback'
			get 'sync(.:format)', :to => 'scripts#sync', :as =>  'sync'
			patch 'sync_update(.:format)', :to => 'scripts#sync_update', :as =>  'sync_update'
			post 'install-ping', :to => 'scripts#install_ping', :as => 'install_ping', :locale => nil
			get 'diff', :to => 'scripts#diff', :as => 'diff', :constraints => lambda{ |req| !req.params[:v1].blank? and !req.params[:v2].blank? }
			get 'delete(.:format)', :to => 'scripts#delete', :as => 'delete'
			post 'delete(.:format)', :to => 'scripts#do_delete', :as => 'do_delete'
			get 'undelete(.:format)', :to => 'scripts#undelete', :as => 'undelete'
			post 'undelete(.:format)', :to => 'scripts#do_undelete', :as => 'do_undelete'
			get 'stats(.:format)', :to => 'scripts#stats', :as => 'stats'
			get 'derivatives', :as => 'derivatives'
			collection do
				get 'by-site(.:format)', :action => 'by_site', :as => 'site_list'
				get 'by-site/:site(.:format)', :action => 'index', :as => 'by_site', :constraints => {:site => /.*?/, :format => /|html|atom|json|jsonp/}
				get 'under-assessment(.:format)', :action => 'under_assessment', :as => 'under_assessment'
				get 'reported(.:format)', :action => 'reported', :as => 'reported'
				get 'libraries(.:format)', :action => 'libraries', :as => 'libraries'
				get 'search(.:format)', :action => 'search', :as => 'search'
				get 'minified(.:format)', :action => 'minified', :as => 'minified'
				get 'code-search(.:format)', :action => 'code_search', :as => 'code_search'
				get 'redistributable(.:format)', :action => 'redistributable', :as => 'redistributable'
			end
			resources :script_versions, :only => [:create, :new, :show, :index], :path => 'versions' do
				get 'delete(.:format)', :to => 'script_versions#delete', :as => 'delete'
				post 'delete(.:format)', :to => 'script_versions#do_delete', :as => 'do_delete'
			end
		end
		resources :script_versions, :only => [:create, :new]
		get 'script_versions/additional_info_form', :to => 'script_versions#additional_info_form', :as => 'script_version_additional_info_form'
		resources :users, :only => :show do
			post 'webhook'
			resources :script_sets, :only => [:create, :new, :edit, :update, :destroy], :path => 'sets'
			get 'ban', :to => 'users#ban', :as => 'ban'
			post 'ban', :to => 'users#do_ban', :as => 'do_ban'
		end
		post 'script_sets/add_to_set', :to => 'script_sets#add_to_set', :as => 'add_to_script_set'

		get 'import', :to => 'import#index', :as => 'import_start'
		get 'import/userscriptsorg', :to => 'import#userscriptsorg', :as => 'import_userscriptsorg'
		post 'import/verify', :to => 'import#verify', :as => 'import_verify'
		post 'import/add', :to => 'import#add', :as => 'import_add'
		get 'import/url', :to => 'import#url', :as => 'import_url'

		get 'help', :to => 'help#index', :as => 'help'
		get 'help/allowed-markup', :to => 'help#allowed_markup', :as => 'help_allowed_markup'
		get 'help/code-rules', :to => 'help#code_rules', :as => 'help_code_rules'
		get 'help/contact', :to => 'help#contact', :as => 'help_contact'
		get 'help/credits', :to => 'help#credits', :as => 'help_credits'
		get 'help/disallowed-code', :to => 'help#disallowed_code', :as => 'help_disallowed_code'
		get 'help/external-scripts', :to => 'help#external_scripts', :as => 'help_external_scripts'
		get 'help/installing-user-scripts', :to => 'help#installing_user_scripts', :as => 'help_installing_user_scripts'
		get 'help/writing-user-scripts', :to => 'help#writing_user_scripts', :as => 'help_writing_user_scripts'
		get 'help/rewriting', :to => 'help#rewriting', :as => 'help_rewriting'
		get 'help/meta-keys', :to => 'help#meta_keys', :as => 'help_meta_keys'
		get 'help/privacy', :to => 'help#privacy', :as => 'help_privacy'

		post 'preview-markup', :to => 'home#preview_markup', :as => 'preview_markup'

		resources :moderator_actions, :only => [:index]

		match '*path', :to => 'home#routing_error', :via => [:get, :post]
	end

	match '*path', :to => 'home#routing_error', :via => [:get, :post]
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
	before_filter :authorize_for_moderators_only, :only => [:disallowed_code]
end

app/helpers/help_helper.rb
module HelpHelper
end

app/views/help/allowed_markup.html.erb
<%- title t('common.allowed_elements_and_attributes_title') %>
<%- description 'Elements and attributes allowed when posting to Greasy Fork.' %>

<p><%=t('common.allowed_elements_intro')%></p>

<ul id="help-allowed-elements">
	<li>* (name, title)</li>
	<li>a (href)</li>
	<li>abbr</li>
	<li>b</li>
	<li>blockquote (cite)</li>
	<li>br</li>
	<li>center</li>
	<li>cite</li>
	<li>code</li>
	<li>dd</li>
	<li>del</li>
	<li>dfn</li>
	<li>div</li>
	<li>dl</li>
	<li>dt</li>
	<li>em</li>
	<li>h1</li>
	<li>h2</li>
	<li>h3</li>
	<li>h4</li>
	<li>h5</li>
	<li>h6</li>
	<li>hr</li>
	<li>i</li>
	<li>ins</li>
	<li>img (alt, height, src (https), width)</li>
	<li>kbd</li>
	<li>li</li>
	<li>mark</li>
	<li>ol</li>
	<li>p</li>
	<li>pre</li>
	<li>q (cite)</li>
	<li>rp</li>
	<li>rt</li>
	<li>ruby</li>
	<li>s</li>
	<li>samp</li>
	<li>small</li>
	<li>span</li>
	<li>strike</li>
	<li>strong</li>
	<li>tt</li>
	<li>table</li>
	<li>tbody</li>
	<li>tfoot</li>
	<li>thead</li>
	<li>td</li>
	<li>th</li>
	<li>tr</li>
	<li>sub</li>
	<li>sup</li>
	<li>time (datetime, pubdate)</li>
	<li>u</li>
	<li>ul</li>
	<li>var</li>
</ul>

<p><%=t('common.allowed_elements_extra_info')%></p>

app/views/help/code_rules.html.erb
<%- title t('help.code_rules.title') %>
<%- description 'Rules and restrictions for code posted to Greasy Fork.' %>

<p>These are the requirements for scripts posted to Greasy Fork. These are intended to keep Greasy Fork a safe and useful place for user scripts. Any script falling outside these requirements may be deleted by Greasy Fork moderators.</p>

<ul>
	<li>Scripts must include a description of what they do and may not do things unreasonably outside of this description. Users must know what a script will do before installing it.</li>
	<li>Code posted to this site must not be obfuscated or minified. Users must be given the opportunity to inspect and understand a script before installing it.</li>
	<li>Libraries that a script uses should be <code>@require</code>-d, unless there's a valid technical reason not to do so. In the case that a library is included inline, it must include information as to the source of the library (e.g. a comment indicating URL and/or name and version).</li>
	<li>Your script must respect others' copyrights. This includes the script itself and any resources (for example images) it uses. If you intend on using someone else's content, abide by their licensing terms or get their permission before doing so.</li>
	<li><%=link_to "Use of external JavaScript is limited.", help_external_scripts_path()%></li>
</ul>

<p>If you notice a script that falls outside of these parameters, please report it by going to the Feedback link for that script, starting a discussion, and choosing the "Report script" option.</p>

<p>If you disagree with any of this, <%=link_to "let's talk about it", help_contact_path()%>!</p>

app/views/help/contact.html.erb
<%- title 'Contact' %>
<%- description 'How to contact someone about Greasy Fork.' %>

<p>There's a bunch of ways to talk about Greasy Fork and the things on it. If you're not sure where or how to do so, this should help.</p>

<p>Do you have a question or comment about a specific script posted on the site? If so, post a discussion from the link on the Feedback tab on that script's page. Script authors get notification on their account page of any discussions on their scripts.</p>

<p>Do you have a question or comment on Greasy Fork itself or on script development, or do you want someone to make you a script? <%=link_to 'Posting in the forum', forum_path%> would give you the widest audience for your discussion.</p>

<p>Do you have a bug report or fully-formed idea for Greasy Fork itself (and not a specific script <em>posted on</em> Greasy Fork)? <a href="https://github.com/JasonBarnabe/greasyfork">Post it on Greasy Fork's GitHub page.</a></p>

<p>Do you have a private question or comment you would like only the admin to see? <a href="mailto:jason.barnabe@gmail.com">Send me an e-mail.</a></p>

app/views/help/credits.html.erb
<%- title t('help.credits.title') %>

<p><%=t('help.credits.authors_credit')%></p>

<p><%=it('help.credits.developers_credit', developers_link: 'https://github.com/JasonBarnabe/greasyfork/graphs/contributors')%></p>

<p><%=it('help.credits.translators_credit', translators_link: 'https://www.transifex.com/organization/greasy-fork/team/21359/')%></p>

<ul>
	<% Locale.where(:ui_available => true).joins(:locale_contributors).order(:code).uniq.each do |locale| %>
		<li><%=locale.native_name%> (<%=locale.code%>): <%=locale.locale_contributors.map{|lc| lc.transifex_user_name}.join(', ')%></li>
	<% end %>
</ul>

<p><%=it('help.credits.icons_credit', vistastylebase: link_to('Vista Style Base Software', 'https://www.iconfinder.com/search/?q=iconset:softwaredemo'), iconsland: link_to('Icons Land', 'http://www.icons-land.com/'), browserlogos: link_to('alrra/browser-logos', 'https://github.com/alrra/browser-logos/'))%></p>

app/views/help/disallowed_code.html.erb
<p>Code patterns that will get blocked automatically. Users posting this will get the message "Name exception (code)".</p>

<p>This is a private list for moderator eyes only, because malicious people could easily craft their scripts to get around these blocks if they knew what they were.</p>

<table>
	<thead>
		<tr>
			<th>Code</th>
			<th>Pattern</th>
			<th>Description</th>
		</tr>
	</thead>
	<tbody>
		<% DisallowedCode.all.each do |dc| %>
			<tr>
				<td><%=dc.ob_code%></td>
				<td><code><%=dc.pattern%></code></td>
				<td><%=dc.description%></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/help/external_scripts.html.erb
<%- title 'Greasy Fork policy on external scripts' %>
<%- description "Greasy Fork's policy on external scripts included in submitted user scripts, for example with @require." %>

<h1>External scripts</h1>

<p>User scripts have the technical ability to load and execute other scripts. The <a href="http://wiki.greasespot.net/Metadata_Block#.40require"><code>@require</code></a> metadata key is the most straightforward way to accomplish this, but scripts can also, for example, use an XmlHttpRequest to download a script and then inject it into the DOM.</p>

<p>While this is a useful feature and most script authors use this for legitimate purposes, it can also be used maliciously. One of the core principles of Greasy Fork is that the user must be able to inspect the code in a script. External scripts can bypass this principle in a number of ways: they can change without warning or history, they can serve up different code to different people, and they can be used to hide malicious code in the middle of known libraries. Even if someone were to check an external script and determine it to be legitimate, that would be no guarantee that that script always has been or always will be legitimate.</p>

<p>To allow script authors to continue to use external scripts, Greasy Fork has implemented a whitelist of URL patterns that can included with a script. This whitelist consists of script locations that:</p>

<ul>
	<li>Are public</li>
	<li>Will not have their contents change frequently</li>
	<li>Would likely be useful to more than one script author</li>
</ul>

<p>The current list is:</p>

<ul>
<% AllowedRequire.all.each do |ar| %>
	<li>
		<% if ar.url.nil? %>
			<%=ar.name%>
		<% else %>
			<%=link_to ar.name, ar.url%>
		<% end %>
	</li>
<% end %>
</ul>

<p>When you post a script that uses a <code>@require</code> outside of these locations, you will be notified when you attempt to save the script. Your script will not be made public on Greasy Fork until this is resolved.</p>

<p>If the script you wish to include is a JavaScript library (for example jQuery or YUI), try to find it on one of the sites listed above. <a href="http://cdnjs.com/">cdnjs</a> and <a href="http://www.jsdelivr.com/">jsDelivr</a> in particular have a wide range of libraries available.</p>

<p>If the script you wish to include is not available on the sites above, <%=link_to 'let us know', help_contact_path()%> and we can find somewhere it is (or host it ourselves!).</p>

<p>If the script you wish to include was written by you, you can submit it as a separate entry on Greasy Fork and choosing the "Library" script type. You will be able to include this posted library in your script.</p>

app/views/help/index.html.erb
<%- title 'Help - Greasy Fork' %>
<%- description 'Help with Greasy Fork.' %>

<ul>
	<li><%=link_to 'How to install user scripts', help_installing_user_scripts_path%></li>
	<li><%=link_to t('help.writing_user_scripts.title'), help_writing_user_scripts_path%></li>
	<li><%=link_to 'Help with Greasemonkey', 'http://wiki.greasespot.net/Troubleshooting_(Users)'%></li>
	<li><%=link_to t('help.meta_keys.title'), help_meta_keys_path%></li>
	<li><%=link_to 'Rules for code posted on Greasy Fork', help_code_rules_path%></li>
	<li><%=link_to 'Rules for code including external scripts', help_external_scripts_path%></li>
	<li><%=link_to 'Allowed markup for posting on Greasy Fork', help_allowed_markup_path%></li>
	<li><%=link_to 'How Greasy Fork will rewrite posted scripts', help_rewriting_path%></li>
	<li><%=link_to 'Report issue or post idea for Greasy Fork itself', 'https://github.com/JasonBarnabe/greasyfork/issues'%></li>
	<li><%=link_to 'Contact someone', help_contact_path%></li>
	<li><%=link_to t('help.credits.title'), help_credits_path%></li>
	<li><%=link_to 'Privacy policy', help_privacy_path%></li>
</ul>

<p>And, not really help topics, but because I have nowhere else to post these...</p>

<ul>
	<li><%=link_to 'User list', users_path%></li>
	<li><%=link_to 'Libraries', libraries_scripts_path%></li>
	<li><%=link_to t('scripts.redistributable_title'), redistributable_scripts_path%></li>
	<li><%=link_to 'Scripts including disallowed external scripts', under_assessment_scripts_path%></li>
	<li><%=link_to 'Reported scripts', reported_scripts_path%></li>
	<li><%=link_to 'Moderator log', moderator_actions_path%></li>
	<li><%=link_to 'Code search', code_search_scripts_path%></li>
</ul>

<% if !current_user.nil? and current_user.moderator? %>
	<p>Hey, moderators.</p>
	<ul>
		<li><%=link_to 'Disallowed code patterns', help_disallowed_code_path%></li>
	</ul>
<% end %>

<p>Greasy Fork is open source (GPLv3 licensed). You can <a href="https://github.com/JasonBarnabe/greasyfork">view its source on GitHub</a>.</p>

app/views/help/installing_user_scripts.html.erb
<%- title 'How to install user scripts' %>
<%- description 'Describes how to install user scripts from Greasy Fork.' %>

<p>How you install user scripts depends on which browser you use. Typically, you will need to install a browser extension. This is not an exhaustive list, please <%=link_to 'contact us', help_contact_path%> if you have any additions.</p>

<p>Once user scripts are enabled in your browser, it should be as simple as clicking the "Install" button on any script's page on Greasy Fork.</p>

<h2>Firefox and related</h2>
<ul>
	<li><a href="https://addons.mozilla.org/firefox/addon/greasemonkey/">Greasemonkey</a></li>
	<li><a href="https://addons.mozilla.org/firefox/addon/scriptish/">Scriptish</a></li>
</ul>

<h2>Google Chrome, Chromium, and related</h2>
<ul>
	<li><a href="https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo">Tampermonkey</a></li>
</ul>

<h2>Opera (version 15 and later)</h2>
<ul>
	<li><a href="https://addons.opera.com/extensions/details/tampermonkey-beta/">Tampermonkey</a></li>
	<li><a href="https://addons.opera.com/extensions/details/violent-monkey/">Violentmonkey</a></li>
</ul>

<h2>Opera (version 12 and earlier)</h2>
<p>Opera version 12 and earlier <a href="http://www.opera.com/docs/userjs/using/#writingscripts">supports user scripts natively</a>. <a href="https://addons.opera.com/extensions/details/violent-monkey/">Violentmonkey</a> provides a friendlier UI and better compatibility.</p>
</ul>

app/views/help/meta_keys.html.erb
<%- title t('help.meta_keys.title') %>
<%- description 'List of user script meta keys that mean something to Greasy Fork.' %>

<p><%=t('help.meta_keys.intro_html')%></p>

<dl>
	<dt><%=self_link('meta-name', '<code>@name</code>')%></dt>
	<dd><%=t('help.meta_keys.name')%></dd>

	<dt><%=self_link('meta-name-localized', '<code>@name:XX-YY</code>')%></dt>
	<dd><%=t('help.meta_keys.name_localized_html')%></dd>

	<dt><%=self_link('meta-description', '<code>@description</code>')%></dt>
	<dd><%=t('help.meta_keys.description')%></dd>

	<dt><%=self_link('meta-name-description', '<code>@description:XX-YY</code>')%></dt>
	<dd><%=t('help.meta_keys.description_localized_html')%></dd>

	<dt><%=self_link('meta-namespace', '<code>@namespace</code>')%></dt>
	<dd><%=t('help.meta_keys.namespace_html')%></dd>

	<dt><%=self_link('meta-version', '<code>@version</code>')%></dt>
	<dd><%=t('help.meta_keys.version_html')%></dd>

	<dt><%=self_link('meta-include', '<code>@include</code>, <code>@exclude</code>, <code>@match</code>')%></dt>
	<dd><%=t('help.meta_keys.include')%></dd>

	<dt><%=self_link('meta-require', '<code>@require</code>')%></dt>
	<dd><%=t('help.meta_keys.require_html', external_script_link: link_to(t('help.meta_keys.require_external_script_link_text'), help_external_scripts_path))%></dd>

	<dt><%=self_link('meta-updateURL', '<code>@updateURL</code>, <code>@installURL</code>, <code>@downloadURL</code>')%></dt>
	<dd><%=t('help.meta_keys.updateURL')%></dd>

	<dt><%=self_link('meta-license', '<code>@license</code>')%></dt>
	<dd><%=t('help.meta_keys.license')%></dd>

	<dt><%=self_link('meta-supportURL', '<code>@supportURL</code>')%></dt>
	<dd><%=t('help.meta_keys.supportURL')%></dd>

	<dt><%=self_link('meta-contributionURL', '<code>@contributionURL</code>')%></dt>
	<dd><%=t('help.meta_keys.contributionURL_html')%></dd>

	<dt><%=self_link('meta-contributionAmount', '<code>@contributionAmount</code>')%></dt>
	<dd><%=t('help.meta_keys.contributionAmount_html')%></dd>

	<% browsers = Browser.select(:code).all.map{|b|"<code>#{b.code}</code>"}.join(', ').html_safe %>
	<dt><%=self_link('meta-compatible', '<code>@compatible</code>')%></dt>
	<dd><%=t('help.meta_keys.compatible_html', browsers: browsers)%></dd>

	<dt><%=self_link('meta-incompatible', '<code>@incompatible</code>')%></dt>
	<dd><%=t('help.meta_keys.incompatible_html', browsers: browsers)%></dd>

</dl>

app/views/help/privacy.html.erb
<%- title 'Privacy policy' %>

<p>This page describes how Greasy Fork will record or track users. If you have any concerns, please e-mail <a href="mailto:jason.barnabe@gmail.com">jason.barnabe@gmail.com</a>.</p>


<h2>Server logs</h2>

<p>Greasy Fork logs all requests in a typical server log fashion. Information logged includes pages visited, IP address, and user agent string. These logs are for debugging and server analysis. The data is retained for one week. This data is not shared or made publicly available.</p>


<h2>Script statistics</h2>

<p>For the purposes of generating statistics, Greasy Fork records install and update requests with IP address information. This information is retained for one day, and then is aggregated to no longer include the IP address. The IP-address-specific data is not shared or made publicly available, but the aggregated data is.</p>


<h2>Cookies (when not logged in)</h2>

<p>Greasy Fork may set temporary session cookies to allow for some site features. These cookies are not set to persist and may cleared when the browser is closed (depending on browser settings).</p>


<h2>User accounts</h2>

<p>Greasy Fork requires users to create an account to post scripts, take part in discussions, and access some other site features. When creating an account, information such as IP address, e-mail address, and user agent may be permanently stored. Some of this information may be made visible to other users.</p>

<p>Actions performed when logged in, for example posting scripts and comments, will be made viewable to other users.</p>

<p>If the "Remember me" option is checked when logging in to an account, Greasy Fork will set a persistent cookie to retain login state.</p>


<h2>Scripts posted on Greasy Fork</h2>

<p>Greasy Fork contains user-generated content, and scripts posted may be able to track users if they install that script.</p>


<h2>Third party libraries</h2>

<p>Greasy Fork may include third party code to collect statistics or display advertisements on the site. These libraries may include tracking logic.</p>

app/views/help/rewriting.html.erb
<%- title 'Script rewriting' %>
<%- description 'A list of ways Greasy Fork may rewrite scripts.' %>

<p>Scripts posted to Greasy Fork may be rewritten in the following ways:</p>

<ul>
	<li><code>@updateURL</code>, <code>@installURL</code>, and <code>@downloadURL</code> directives will be stripped, if present. The lack of these directives means that any script installed from Greasy Fork will be updated from Greasy Fork.</li>
	<li><code>@version</code> and <code>@namespace</code> directives will be inserted if the script is missing them. These directives are needed for proper updating.</li>
	<li><code>@description</code> will be inserted if a new version of a script is missing it and a previous version of the script had it.</li>
	<li>Line breaks will be converted to Unix-style line breaks (\n).</li>
</ul>

app/views/help/writing_user_scripts.html.erb
<% title t('help.writing_user_scripts.title') %>

<%=t('help.writing_user_scripts.content_html',
	code_rules_link: link_to(t('help.code_rules.title'), help_code_rules_path),
	meta_keys_link: link_to(t('help.meta_keys.title'), help_meta_keys_path),
	ask_in_forum_link: link_to(t('help.writing_user_scripts.ask_in_forum_link_text'), forum_path),
	user_page_link: current_user.nil? ? t('help.writing_user_scripts.user_page_link_text') : link_to(t('help.writing_user_scripts.user_page_link_text'), current_user),
	post_new_script_link: link_to(t('help.writing_user_scripts.post_new_script_link_text'), new_script_version_path)
)%>