config/routes.rb
Greasyfork::Application.routes.draw do

	get 'sso', :to => 'home#sso'

	scope "(:locale)", locale: /ar|bg|cs|de|el|en|es|fi|fr|fr\-CA|id|it|ja|nb|nl|pl|pt\-BR|ru|tr|uk|vi|zh\-CN|zh\-TW/ do

		get '/users', :to => 'users#index', :as => 'users'
		get '/users/webhook-info', :to => 'users#webhook_info', :as => 'user_webhook_info'
		post 'users/webhook-info', :to => 'users#webhook_info'
		get '/users/edit_sign_in' => 'users#edit_sign_in', :as => 'user_edit_sign_in'
		delete '/users/identities' => 'users#delete_identity', :as => 'user_delete_identity'
		put '/users/identities' => 'users#update_identity', :as => 'user_update_identity'
		put '/users/remove_password' => 'users#remove_password', :as => 'user_remove_password'
		put '/users/update_password' => 'users#update_password', :as => 'user_update_password'

		get '/external_login', :as => 'external_login', to: 'home#external_login'

		devise_for :users, :skip => :registrations, :controllers => { :sessions => "sessions" }
		devise_scope :user do
			resource :registration,
			only: [:new, :create, :edit, :update],
			path: 'users',
			path_names: { new: 'sign_up' },
			controller: :registrations,
			as: :user_registration do
				get :cancel
			end
		end
		devise_scope :user do
			get '/users/sign_out' => 'sessions#destroy'
			get '/auth/:provider/callback', to: 'sessions#omniauth_callback', :as => 'omniauth_callback'
			post '/auth/:provider/callback', to: 'sessions#omniauth_callback'
			get '/auth/failure', to: 'sessions#omniauth_failure'
			get '/auth/failure2', to: 'sessions#omniauth_failure'
			post '/auth/name_conflict', to: 'sessions#name_conflict'
		end

		root :to => "home#index"

		get 'scripts/sync_additional_info_form', :to => 'scripts#sync_additional_info_form', :as => 'script_sync_additional_info_form'
		resources :scripts, :only => [:index, :show] do
			get 'code.meta.js', :to => 'scripts#meta_js', :locale => nil
			get 'code.user.js', :to => 'scripts#user_js', :locale => nil

			get 'code/:name.user.js', :to => 'scripts#user_js', :as =>  'user_js', :locale => nil
			get 'code/:name.js', :to => 'scripts#user_js', :as =>  'library_js', :locale => nil
			get 'code/:name.meta.js', :to => 'scripts#meta_js', :as =>  'meta_js', :locale => nil
			match 'code/:name.meta.js', :to => 'scripts#meta_js', :locale => nil, :via => :options
			get 'code(.:format)', :to => 'scripts#show_code', :as =>  'show_code', :constraints => {:format => /.*/}
			get 'feedback(.:format)', :to => 'scripts#feedback', :as =>  'feedback'
			get 'sync(.:format)', :to => 'scripts#sync', :as =>  'sync'
			patch 'sync_update(.:format)', :to => 'scripts#sync_update', :as =>  'sync_update'
			post 'install-ping', :to => 'scripts#install_ping', :as => 'install_ping', :locale => nil
			get 'diff', :to => 'scripts#diff', :as => 'diff', :constraints => lambda{ |req| !req.params[:v1].blank? and !req.params[:v2].blank? }
			get 'delete(.:format)', :to => 'scripts#delete', :as => 'delete'
			post 'delete(.:format)', :to => 'scripts#do_delete', :as => 'do_delete'
			get 'undelete(.:format)', :to => 'scripts#undelete', :as => 'undelete'
			post 'undelete(.:format)', :to => 'scripts#do_undelete', :as => 'do_undelete'
			get 'stats(.:format)', :to => 'scripts#stats', :as => 'stats'
			get 'derivatives', :as => 'derivatives'
			collection do
				get 'by-site(.:format)', :action => 'by_site', :as => 'site_list'
				get 'by-site/:site(.:format)', :action => 'index', :as => 'by_site', :constraints => {:site => /.*?/, :format => /|html|atom|json|jsonp/}
				get 'under-assessment(.:format)', :action => 'under_assessment', :as => 'under_assessment'
				get 'reported(.:format)', :action => 'reported', :as => 'reported'
				get 'libraries(.:format)', :action => 'libraries', :as => 'libraries'
				get 'search(.:format)', :action => 'search', :as => 'search'
				get 'minified(.:format)', :action => 'minified', :as => 'minified'
				get 'code-search(.:format)', :action => 'code_search', :as => 'code_search'
				get 'redistributable(.:format)', :action => 'redistributable', :as => 'redistributable'
			end
			resources :script_versions, :only => [:create, :new, :show, :index], :path => 'versions' do
				get 'delete(.:format)', :to => 'script_versions#delete', :as => 'delete'
				post 'delete(.:format)', :to => 'script_versions#do_delete', :as => 'do_delete'
			end
		end
		resources :script_versions, :only => [:create, :new]
		get 'script_versions/additional_info_form', :to => 'script_versions#additional_info_form', :as => 'script_version_additional_info_form'
		resources :users, :only => :show do
			post 'webhook'
			resources :script_sets, :only => [:create, :new, :edit, :update, :destroy], :path => 'sets'
			get 'ban', :to => 'users#ban', :as => 'ban'
			post 'ban', :to => 'users#do_ban', :as => 'do_ban'
		end
		post 'script_sets/add_to_set', :to => 'script_sets#add_to_set', :as => 'add_to_script_set'

		get 'import', :to => 'import#index', :as => 'import_start'
		get 'import/userscriptsorg', :to => 'import#userscriptsorg', :as => 'import_userscriptsorg'
		post 'import/verify', :to => 'import#verify', :as => 'import_verify'
		post 'import/add', :to => 'import#add', :as => 'import_add'
		get 'import/url', :to => 'import#url', :as => 'import_url'

		get 'help', :to => 'help#index', :as => 'help'
		get 'help/allowed-markup', :to => 'help#allowed_markup', :as => 'help_allowed_markup'
		get 'help/code-rules', :to => 'help#code_rules', :as => 'help_code_rules'
		get 'help/contact', :to => 'help#contact', :as => 'help_contact'
		get 'help/credits', :to => 'help#credits', :as => 'help_credits'
		get 'help/disallowed-code', :to => 'help#disallowed_code', :as => 'help_disallowed_code'
		get 'help/external-scripts', :to => 'help#external_scripts', :as => 'help_external_scripts'
		get 'help/installing-user-scripts', :to => 'help#installing_user_scripts', :as => 'help_installing_user_scripts'
		get 'help/writing-user-scripts', :to => 'help#writing_user_scripts', :as => 'help_writing_user_scripts'
		get 'help/rewriting', :to => 'help#rewriting', :as => 'help_rewriting'
		get 'help/meta-keys', :to => 'help#meta_keys', :as => 'help_meta_keys'
		get 'help/privacy', :to => 'help#privacy', :as => 'help_privacy'

		post 'preview-markup', :to => 'home#preview_markup', :as => 'preview_markup'

		resources :moderator_actions, :only => [:index]

		match '*path', :to => 'home#routing_error', :via => [:get, :post]
	end

	match '*path', :to => 'home#routing_error', :via => [:get, :post]
end

app/models/script_type.rb
class ScriptType < ActiveRecord::Base
end

app/helpers/scripts_helper.rb
module ScriptsHelper

	def script_list_link(label, sort = nil, site = nil, set = nil, current_set = nil)
		is_link = true
		is_search = action_name == 'search'
		is_minified = action_name == 'minified'
		is_code_search = action_name == 'code_search'
		# sets can have a different default
		sort_param_to_use = (!current_set.nil? && sort == current_set.default_sort) ? nil : sort
		# if everything in the current page is the same as what we would link too, don't link!
		if sort_param_to_use == params[:sort] and (is_search or site == params[:site]) and ((set.nil? and params[:set].nil?) or set.to_s == params[:set])
			l = label
			is_link = false
		elsif is_search
			l = link_to label, search_scripts_path(:sort => sort_param_to_use, :q => params[:q], :set => set)
		elsif is_minified
			l = link_to label, minified_scripts_path(:sort => sort_param_to_use)
		elsif is_code_search
			l = link_to label, code_search_scripts_path(:sort => sort_param_to_use, :c => params[:c])
		elsif site.nil?
			l = link_to label, {:sort => sort_param_to_use, :set => set, :site => nil}
		elsif params[:controller] == 'users'
			l = link_to label, {:sort => sort_param_to_use, :site => site, :set => set}
		else
			l = link_to label, by_site_scripts_path(:sort => sort_param_to_use, :site => site, :set => set)
		end
		return ("<li class=\"list-option#{is_link ? '' : ' list-current'}\">" + l + '</li>').html_safe
	end

	def script_applies_to_list_contents(script, by_sites)
		sats_with_domains, sats_without_domains = script.script_applies_tos.partition{|sat|sat.domain}
		return (
		sats_with_domains.map{ |sat|			
			content_for_script_applies_to_that_has_domain(sat, count_of_other_scripts_with_sat(sat, script, by_sites))
		} +
		sats_without_domains.map{ |sat| content_tag(:code, sat.text) }
		)
	end

private

	def content_for_script_applies_to_that_has_domain(sat, count_of_other_scripts)
		if count_of_other_scripts > 0
			title = t('scripts.applies_to_link_title', {:count => count_of_other_scripts, :site => sat.text})
			return link_to(sat.text, by_site_scripts_path(:site => sat.text), {:title => title})
		end
		return sat.text
	end

	def count_of_other_scripts_with_sat(script_applies_to, script, by_sites)
		return 0 if by_sites[script_applies_to.text].nil?
		# take this one out of the count if it's a listable
		return (by_sites[script_applies_to.text][:scripts] - (script.listable? ? 1 : 0))
	end

end

app/views/scripts/_list_options.html.erb
<div id="script-list-option-groups" class="list-option-groups">
	<div id="script-list-sort" class="list-option-group"><%=t('scripts.listing_sort_label')%>
		<ul>
			<% if action_name == 'search' %>
				<%=script_list_link(t('scripts.listing_sort_relevance'), nil, params[:site], params[:set], @set)%>
				<%=script_list_link(t('scripts.listing_sort_daily_installs'), 'daily_installs', params[:site], params[:set], @set)%>
			<% elsif defined?(@set) && !@set.nil? && !@set.default_sort.nil? %>
				<%=script_list_link(t('scripts.listing_sort_daily_installs'), 'daily_installs', params[:site], params[:set], @set)%>
			<% else %>
				<%=script_list_link(t('scripts.listing_sort_daily_installs'), nil, params[:site], params[:set], @set)%>
			<% end %>
			<%=script_list_link(t('scripts.listing_sort_total_installs'), 'total_installs', params[:site], params[:set], @set)%>
			<%=script_list_link(t('scripts.listing_sort_ratings'), 'ratings', params[:site], params[:set], @set)%>
			<%=script_list_link(t('scripts.listing_sort_created_date'), 'created', params[:site], params[:set], @set)%>
			<%=script_list_link(t('scripts.listing_sort_updated_date'), 'updated', params[:site], params[:set], @set)%>
			<%=script_list_link(t('scripts.listing_sort_name'), 'name', params[:site], params[:set], @set)%>
		</ul>
	</div>

	<% if !by_sites.nil? %>
		<div id="script-list-filter" class="list-option-group"><%=t('scripts.listing_filter_by_site_label')%>
			<ul>
				<%=script_list_link(t('scripts.listing_filter_by_site_disable'), params[:sort], nil, params[:set])%>
				<% current_site_is_top = false
				(0..9).each do |i|
					break if by_sites[i].nil?
					dt = by_sites[i][0]
					if dt.nil?
						current_site_is_top = true if params[:site] == '*' %>
						<%=script_list_link(t('scripts.listing_filter_by_site_all_sites'), params[:sort], '*', params[:set], @set)%>
					<% else
						current_site_is_top = true if dt == params[:site] %>
						<%=script_list_link(dt, params[:sort], dt, params[:set], @set)%>
					<% end %>
				<% end %>
				<% if !current_site_is_top and !params[:site].nil? and !scripts.empty? %>
					<%=script_list_link(params[:site], params[:sort], params[:site], @set)%>
				<% end %>
				<li><%= link_to t('scripts.listing_filter_by_site_more_sites'), site_list_scripts_path %></li>
			</ul>
		</div>
	<% end %>

	<% # This doesn't work for search
	if action_name != 'search' && user_signed_in? && !current_user.script_sets.empty? %>
		<div id="script-list-set" class="list-option-group">Script set:
			<ul>
				<%=script_list_link('All', params[:sort], params[:site], nil, @set)%>
				<% ScriptSet.favorites_first(current_user.script_sets).each do |set| %>
					<%=script_list_link(set.display_name, params[:sort], params[:site], set.id, @set)%>
				<% end %>
			</ul>
		</div>

	<% end %>
</div>

app/views/scripts/_ratings.html.erb
<span class="good-rating-count" title="<%=t('scripts.good_rating_explanation')%>"><%=script.good_ratings%></span>
<span class="ok-rating-count" title="<%=t('scripts.ok_rating_explanation')%>"><%=script.ok_ratings%></span>
<span class="bad-rating-count" title="<%=t('scripts.bad_rating_explanation')%>"><%=script.bad_ratings%></span>

app/views/scripts/_script.html.erb
<% translation_cache = {} if !defined?(translation_cache) || translation_cache.nil? %>
<li data-script-id="<%=script.id%>" data-script-name="<%=script.name(I18n.locale)%>" data-script-author-id="<%=script.user.id%>" data-script-author-name="<%=script.user.name%>" data-script-daily-installs="<%=script.daily_installs%>" data-script-total-installs="<%=script.total_installs%>" data-script-rating-score="<%=script.fan_score%>" data-script-created-date="<%=script.created_at.strftime('%Y-%m-%d')%>" data-script-updated-date="<%=script.code_updated_at.strftime('%Y-%m-%d')%>" data-script-type="<%=script.script_type.short_name%>" data-script-version="<%=script.version%>">
	<article>
		<h2>
			<%=link_to script.name(I18n.locale), script_path(script)%>
			<% if script.script_type_id != 1 %>
				<span class="script-type">(<%=script.script_type.short_name.capitalize%>)</span>
			<% end %>
			<% if script.deleted? %>
				<span class="script-type">(Deleted)</span>
			<% end %>
			<% if script.locked %>
				<span class="script-type">(Locked)</span>
			<% end %>
			<span class="name-description-separator">
				-
			</span>
			<span class="description">
				<%=script.description(I18n.locale)%>
			</span>
		</h2>
		<dl>
			<dt class="script-list-author"><span><%=translation_cache['scripts.author_name'] || t('scripts.author_name')%></span></dt>
			<dd class="script-list-author"><span><%=link_to script.user.name, user_path(script.user)%></span></dd>
			<dt class="script-list-daily-installs"><span><%=translation_cache['scripts.daily_installs'] || t('scripts.daily_installs')%></span></dt>
			<dd class="script-list-daily-installs"><span><%=number_with_delimiter(script.daily_installs)%></span></dd>
			<dt class="script-list-total-installs"><span><%=translation_cache['scripts.total_installs'] || t('scripts.total_installs')%></span></dt>
			<dd class="script-list-total-installs"><span><%=number_with_delimiter(script.total_installs)%></span></dd>
			<dt class="script-list-ratings"><span><%=translation_cache['scripts.ratings'] || t('scripts.ratings')%></span></dt>
			<dd class="script-list-ratings" data-rating-score="<%=script.fan_score%>"><span><%=render :partial => 'scripts/ratings', :locals => {:script => script}%></span></dd>
			<dt class="script-list-created-date"><span><%=translation_cache['scripts.created_date'] || t('scripts.created_date')%></span></dt>
			<dd class="script-list-created-date"><span><%=markup_date(script.created_at)%></span></dd>
			<dt class="script-list-updated-date"><span><%=translation_cache['scripts.updated_date'] || t('scripts.updated_date')%></span></dt>
			<dd class="script-list-updated-date"><span><%=markup_date(script.code_updated_at)%></span></dd>
		</dl>
	</article>
</li>

app/views/scripts/delete.html.erb
<%- title "Delete #{@script.name}" %>

<% moderator_view = current_user.moderator? && current_user != @script.user %>
<%=form_tag(script_do_delete_path) do |f|%>

	<% if !@script.errors.empty? %>
		<div class="alert">
			<p><%=t('common.error_preamble')%></p>
			<ul class="errors">
				<% @script.errors.full_messages.each do |e| %>
					<li><%=e%></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<% ScriptDeleteType.all.each do |sdt|
			if params[:script_delete_type_id].nil?
				selected = sdt.id == 2 && moderator_view
			else
				selected = params[:script_delete_type_id] == sdt.id.to_s
			end %>
			<input type="radio" required id="script_delete_type_id_<%=sdt.id%>" name="script_delete_type_id" value="<%=sdt.id%>" <%if selected%>checked<%end%>> <label for="script_delete_type_id_<%=sdt.id%>"><%=sdt.description%></label><br>
		<% end %>
	</p>
	<p>
		<label for="replaced_by_script_id"><%=t('scripts.replacement_script_explanation')%></label>
		<input id="replaced_by_script_id" name="replaced_by_script_id" value="<%=params[:replaced_by_script_id] || @script.replaced_by_script_id%>">
	</p>
	<% if moderator_view %>
		<p>
			<label for="reason">Why are you deleting this?</label><br>
			<textarea id="reason" name="reason" rows="5" cols="100" maxlength="500" required></textarea>
		</p>
		<p>
			<label for="locked">Lock the script to prevent undelete by the author?</label> <input type="checkbox" id="locked" name="locked" value="1" checked>
		</p>
		<% if @script.user.banned %>
			<p>(User already banned.)</p>
		<% else %>
			<p>
				<label for="banned">Ban this user?</label> <input type="checkbox" id="banned" name="banned" value="1">
			</p>
		<% end %>
		<p>This user has <%=link_to("#{@other_scripts} other non-locked scripts", @script.user)%>.</p>
	<% end %>
	<input type="submit" value="Delete">
<% end %>

app/views/scripts/derivatives.html.erb
<%- title t('scripts.derivatives_title', :script_name => @script.name) %>
<%- description 'Potential derivatives of ' + @script.name %>

<p><%=t('scripts.derivatives_intro')%></p>

<% if !CpdDuplication.first.nil? %>
	<p><%=t('scripts.derivatives_code_matches_info_html', {:last_run => markup_date(CpdDuplication.first.created_at), :max_size => number_to_human_size(Rails.configuration.cpd_size_limit), :match_size => 100})%></p>
	<% if @code_duplications.empty? %>
		<p><%=t('scripts.listing_none')%></p>
	<% else %>
		<ul>
			<% # line number starts at 0 in CPD but at 1 for us, so +1 to everything
			@code_duplications.each do |cd|
				source_duplications = cd.cpd_duplication_scripts.select{|cpdds| cpdds.script_id == @script.id}
				source_duplications.each do |source_duplication| %>
					<li>
						<%=link_to t('scripts.script_lines_link', {:script_name => @script.name, :start => source_duplication.line + 1, :end => source_duplication.line + cd.lines + 1}), script_show_code_path(source_duplication.script, :anchor => "n#{source_duplication.line + 1}")%>
						<ul>
							<% cd.cpd_duplication_scripts.select{|cpdds| cpdds.script.user_id != @script.user_id && cpdds.script.listable?}.each do |dup| %>
								<li>
									<%=t('scripts.derivatives_script_with_code_line_html',  {
										:script_lines_link => link_to(
											t('scripts.script_lines_link', {
												:script_name => dup.script.name(I18n.locale),
												:start => dup.line + 1,
												:end => dup.line + cd.lines + 1
											}),
											script_show_code_path(dup.script, :anchor => "n#{dup.line + 1}")
										),
										:license => dup.script.license_display,
										:user_link => link_to(dup.script.user.name, dup.script.user)
									})%>
								</li>
							<% end %>
						</ul>
					</li>
				<% end
			end %>
		</ul>
	<% end %>
<% end %>

<% if !@script.namespace.nil? %>
	<%=render :partial => 'derivatives_list', :locals => {:description => t('scripts.derivatives_namespace_matches_info_html', :namespace => "@namespace #{@script.namespace}"), :scripts => @same_namespaces} %>
<% end %>

<%=render :partial => 'derivatives_list', :locals => {:description => t('scripts.derivatives_name_matches_info'), :scripts => @similar_name_scripts} %>

app/views/scripts/index.html.erb
<%- title @title %>
<%- description @description %>

<%= render partial: 'list_options', :locals => {:by_sites => @by_sites, :scripts => @scripts}%>

<% if defined?(@set) and !@set.nil? %>
	<h3>
		<%=@set.display_name%> by <%=link_to @set.user.name, @set.user%>
		<% if user_signed_in? and current_user == @set.user%>
			<%=link_to('Edit', edit_user_script_set_path(current_user, @set))%>
		<% end %>
	</h3>
	<% if !@set.favorite %>
		<p><%=@set.description%></p>
	<% end %>
<% end %>

<% if defined?(@page_description) %>
	<p><%=@page_description%></p>
<% end %>

<% if @scripts.empty? %>
	<p><%=t('scripts.listing_no_scripts')%></p>
<% else %>
	<ol id="browse-script-list" class="script-list">
		<%= render partial: 'script', collection: @scripts, locals: {:translation_cache => translate_keys(['scripts.author_name', 'scripts.daily_installs', 'scripts.total_installs', 'scripts.ratings', 'scripts.created_date', 'scripts.updated_date']) } %>
	</ol>
<% end %>

<% if !defined?(@paginate) or @paginate %>
	<%= will_paginate @scripts %>
<% end %>

<p><%=t('scripts.write_your_own_html', post_a_script_link: link_to(t('scripts.post_a_script_link_text'), new_script_version_path), learn_to_write_scripts_link: link_to(t('scripts.learn_to_write_scripts_link_text'), help_writing_user_scripts_path)) %></p>

app/views/scripts/libraries.html.erb
<%- title 'Libraries on Greasy Fork' %>
<%- description 'List of user-submitted libraries available on Greasy Fork' %>

<h1>Libraries</h1>
<p>There are libraries posted by Greasy Fork users that you can @require in your scripts. For other kinds of libraries you can @require, <%=link_to 'read Greasy Fork\'s policy on <code>@require</code>.'.html_safe, help_code_rules_path(:anchor => 'require')%></p>
<% if @scripts.empty? %>
	<p>No libraries currently posted.</p>
<% else %>
	<ul>
		<% @scripts.each do |script| %>
			<li>
				<%=link_to script.name(I18n.locale), script %> <%=script.description%>
			</li>
		<% end %>
	</ul>
<% end %>

app/views/scripts/sync.html.erb
<% if !@script.errors.empty? %>
	<div class="alert">
		<p><%=t('common.error_preamble')%></p>
		<ul class="errors">
			<% @script.errors.full_messages.each do |m| %>
				<li><%=m%></li>
			<% end %>
		</ul>
	</div>
<% end %>

<%=form_for(@script, :url => script_sync_update_path) do |s|%>

	<% case @script.script_sync_source_id 
		when 1 %>
			<p>
				<%=t('scripts.code_syncing_from_url_html', :field => s.url_field(:sync_identifier, :size => 50, :placeholder => t('scripts.sync_url_placeholder')))%>
			</p>
		<% when nil %>
			<p>
				<%=t('scripts.provide_code_syncing_from_url_html', :field => s.url_field(:sync_identifier, :size => 50, :placeholder => t('scripts.sync_url_placeholder')))%>
			</p>
	<% end %>

	<div class="radio-group">
		<%=t('scripts.sync_type_intro')%><br>
		<%=s.radio_button(:script_sync_type_id, 2)%> <label for="script_script_sync_type_id_2"><%=t('scripts.sync_type_2')%></label><br>
		<%=s.radio_button(:script_sync_type_id, 1)%> <label for="script_script_sync_type_id_1"><%=t('scripts.sync_type_1')%></label><br>
		<% # only allow changing *off* of Webhook - setting it to Webhook is done when a push comes in
		if @script.script_sync_type_id == 3 %>
			<%=s.radio_button(:script_sync_type_id, 3)%> <label for="script_script_sync_type_id_3"><%=t('scripts.sync_type_3')%></label><br>
		<% end %>
	</div>

	<div>
		<p>You can optionally sync your script's additional info.</p>
		<div class="indented">
			<% localized_additional_infos = @script.localized_attributes_for('additional_info').select{|la| la.attribute_default || !la.sync_identifier.nil? || la.new_record?}
			localized_additional_infos.each_with_index do |la, index| %>
				<%=render :partial => 'sync_additional_info', :locals => {:la => la, :index => index, :preview => @preview.nil? ? nil : @preview[index]}%>
			<% end %>
			<div>
				<button id="add-synced-additional-info" name="add-synced-additional-info" value="1" type="submit">Add a localized, synced additional info</button>
			</div>
		</div>
	</div>

	<% if !@script.script_sync_source_id.nil? %>
		<p>
			<% if !@script_sync_error.nil? %>
				<%=t('scripts.sync_failed_info_html', {:date => markup_date(@script.last_attempted_sync_date), :error => @script.sync_error})%>
			<% end %>
			<% if @script.last_successful_sync_date.nil? %>
				<%=t('scripts.sync_never_succeeded')%>
			<% else %>
				<%=t('scripts.sync_success_info_html', {:date => markup_date(@script.last_successful_sync_date)})%>
			<% end %>
		</p>
	<% end %>
	<p>
		<% if @script.script_sync_source_id.nil? %>
			<input type="submit" name="update-and-sync" value="<%=t('scripts.update_and_sync')%>">
		<% else %>
			<input type="submit" name="update-only" value="<%=t('scripts.update_no_sync')%>">
			<input type="submit" name="update-and-sync" value="<%=t('scripts.update_and_sync')%>">
			<input type="submit" name="stop-syncing" value="<%=t('scripts.turn_off_syncing')%>">
		<% end %>
	</p>

<% end %>

app/views/scripts/undelete.html.erb
<%- title "Undelete #{@script.name}" %>

<% moderator_view = current_user.moderator? && current_user != @script.user %>
<%=form_tag(script_do_undelete_path) do |f|%>
	<% if moderator_view %>
		<p>
			<label for="reason">Why are you undeleting this?</label><br>
			<textarea id="reason" name="reason" rows="5" cols="100" maxlength="500" required></textarea>
		</p>
		<% if @script.user.banned %>
			<p>
				<label for="unbanned">Unban this user?</label> <input type="checkbox" id="unbanned" name="unbanned" value="1">
			</p>
		<% end %>
	<% end %>
	<input type="submit" value="Undelete">
<% end %>

app/views/scripts/under_assessment.html.erb
<h1>Scripts including disallowed external scripts</h1>
<p><%=link_to 'Read Greasy Fork\'s policy on external scripts.', help_external_scripts_path%></p>
<% if @scripts.empty? %>
	<p>No scripts currently under assessment.</p>
<% else %>
	<ul>
		<% @scripts.each do |script| %>
			<li>
				<%=link_to script.name(I18n.locale), script %> <%=script.assessments.map{|a| a.assessment_reason.name + ' ' + a.details}.join(', ')%>
			</li>
		<% end %>
	</ul>
<% end %>